# Generated by Django 5.2.1 on 2025-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('profissao', models.CharField(max_length=100)),
                ('estado_natal', models.CharField(max_length=2)),
                ('cidade_natal', models.CharField(max_length=100)),
                ('estado_residencia', models.CharField(max_length=2)),
                ('cidade_residencia', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo'), ('União Estável', 'União Estável')], max_length=20)),
                ('contato_emergencia', models.CharField(max_length=15)),
                ('intencao_doar', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('profissao', models.CharField(max_length=100)),
                ('estado_natal', models.CharField(max_length=2)),
                ('cidade_natal', models.CharField(max_length=100)),
                ('estado_residencia', models.CharField(max_length=2)),
                ('cidade_residencia', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viuvo', 'Viúvo'), ('União Estável', 'União Estável')], max_length=20)),
                ('contato_emergencia', models.CharField(max_length=15)),
                ('orgao_necessario', models.CharField(max_length=50)),
                ('gravidade_condicao', models.CharField(max_length=50)),
                ('centro_transplante_vinculado', models.CharField(max_length=100)),
                ('posicao_lista_espera', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
