# Generated by Django 5.2.1 on 2025-06-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptor',
            old_name='centro_transplante_vinculado',
            new_name='centro_transplante',
        ),
    ]
