# Generated by Django 5.2.1 on 2025-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_rename_centro_transplante_vinculado_receptor_centro_transplante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='idade',
        ),
    ]
